matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.2

# before_install:
#   - echo "$TRAVIS_OS_NAME"
#   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bin/install-swift.sh; fi

env:
  - SWIFT_VERSION=5.1-RELEASE
language:
  - swift
script:
  - swift test --parallel
