matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.2

before_install:
  - echo "$TRAVIS_OS_NAME"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bin/install-swift.sh; fi

language:
  - swift
script:
  - swift test --parallel
