on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

name: Test
jobs:
  test:
    name: Test
    runs-on: macos-latest
    # Set timeout to prevent overcharging
    timeout-minutes: 20
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: 12.5
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test --parallel
