on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

name: Test
jobs:
  test:
    name: Test
    runs-on: macos-latest
    # Set timeout to prevent overcharging
    timeout-minutes: 20
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: swift test --parallel
